### ISSUE TITLE
JOSS Review: Clarify license text

### ISSUE THREAD

**Issue by willu47** [IMMM-SFA/cerf#37]
Part of openjournals/joss-reviews#3601

Could you clarify that the license text is identical to the [OSI approved 2-clause BSD](https://opensource.org/licenses/BSD-2-Clause)?

- [x] The text formatting of the clauses appears to differ
- [x] the SPDX short identifier differs from `BSD-2-Clause`

**Comment by willu47** [comment]
I also note that an earlier version (v1.0.0) of cerf appears to contain GPL licensed C code, which may be incompatible with the BSD license. It may be worth checking this.

**Comment by crvernon** [comment]
Thanks @willu47 .  I had our legal look into the inclusion of GPL products without replication when setting up the original license in 2018.  I will review that documentation and provide clarity.  Also, I will modify the license text to be identical with the OSI approved text and use the correct SPDX short id in the setup args.
