### ISSUE TITLE
JOSS Review: Installation

### ISSUE THREAD

**Issue by willu47** [IMMM-SFA/cerf#39]
Part of openjournals/joss-reviews#3601

I used miniconda to create a new Python 3.9 environment on OSX 10.15.7 and then ran the command `pip install cerf`. This installed all dependencies without a problem.

- [x] Improve readme for the quickstart tutorial. Dependencies (e.g. Jupyter) for the tutorial notebooks are not installed, and the quickstart tutorial is not available when installing the cerf package (e.g. it is not placed anywhere on the user computer). This would be confusing for a beginner user.  It might be simpler to integrate the information in the notebook into the documentation, and make the notebook downloadable from the docs (with separate installation instructions for the tutorial there).

**Comment by willu47** [comment]
Hi @crvernon - I think for all these review issues, viewing the final merged product is easiest. Do reference the issue in your PR so I can follow along. I won't have time to review every PR and would prefer you do that in-house.

**Comment by crvernon** [comment]
@willu47 Sounds great to me.  I'll keep them rolling.  I appreciate the prompt and valuable feedback.
